### ISSUE TITLE
Dynamax/R1 Pro Treadmill not working properly

### ISSUE THREAD

**Issue by Turkules** [huserben/walkingpad#11]
I have a Dynamax Treadmill, which is the same as the R1 Pro without the capabilities to connect to the KSFitApp. I am not able to successfully change the mode of the Treadmill, what could be wrong here? Moreoever, i would appreciate it if you could help me out in how to export the counted steps to a CSV in this specific software solution. I am running the program on a Raspberry Pi 4.

```
* Serving Flask app 'restserver'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5678
 * Running on http://192.168.178.79:5678
Press CTRL+C to quit
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 478-590-251
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:47:46] "GET /mode?new_mode=standby HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/dist-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/alcom/walkingpad/restserver.py", line 106, in get_pad_mode
    await connect()
  File "/home/alcom/walkingpad/restserver.py", line 78, in connect
    await ctler.run(address)
  File "/home/alcom/.local/lib/python3.9/site-packages/ph4_walkingpad/pad.py", line 388, in run
    await self.connect(address)
  File "/home/alcom/.local/lib/python3.9/site-packages/ph4_walkingpad/pad.py", line 308, in connect
    return await self.client.connect(timeout=10.0, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bleak/__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/client.py", line 190, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Disconnected early
192.168.178.27 - - [05/Feb/2023 17:47:46] "GET / HTTP/1.1" 404 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 07, 00, 01, 00, ab, fd
Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:48:23] "GET /mode?new_mode=standby. HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 07, 00, 00, 00, aa, fd
Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:48:30] "GET /mode?new_mode=standby HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 07, 00, 00, 00, aa, fd
Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:48:59] "GET /mode?new_mode=standby HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 07, 00, 00, 00, aa, fd
Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:49:14] "GET /mode?new_mode=standby HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 07, 00, 00, 00, aa, fd
Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:49:21] "GET /mode?new_mode=automatic HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:49:45] "GET /mode?new_mode=automatic HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/dist-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/alcom/walkingpad/restserver.py", line 106, in get_pad_mode
    await connect()
  File "/home/alcom/walkingpad/restserver.py", line 78, in connect
    await ctler.run(address)
  File "/home/alcom/.local/lib/python3.9/site-packages/ph4_walkingpad/pad.py", line 388, in run
    await self.connect(address)
  File "/home/alcom/.local/lib/python3.9/site-packages/ph4_walkingpad/pad.py", line 308, in connect
    return await self.client.connect(timeout=10.0, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bleak/__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/client.py", line 190, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Disconnected early
192.168.178.27 - - [05/Feb/2023 17:49:45] "GET /mode?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
192.168.178.27 - - [05/Feb/2023 17:49:45] "GET /mode?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
192.168.178.27 - - [05/Feb/2023 17:49:45] "GET /mode?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 01, 0f, 01, 00, 00, 14, 00, 00, 00, 00, 00, 17, 07, 00, 04, 00, e9, fd
Status: WalkingPadCurStatus(dist=0.0, time=20, steps=23, speed=1.5, state=1, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Msg: f8, b2, 0c, 09, 01, 0c, 0f, 0d, 00, 14, 0a, 00, 17, 0e, 3c, 6f, fd
Msg: f8, b2, 05, 19, 63, df, de, 24, 14, fd
Msg: f8, b2, 07, 02, 00, 01, 0b, 00, 00, 3e, 05, fd
Disconnecting
Msg: f8, b2, 03, 0d, 00, 16, d8, fd
Msg: f8, b2, 03, 0a, 00, 19, d8, fd
Msg: f8, b2, 03, 0a, 00, 1b, da, fd
192.168.178.27 - - [05/Feb/2023 17:50:05] "GET /mode?new_mode=automatic HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 01, 0f, 01, 00, 00, 33, 00, 00, 02, 00, 00, 49, 07, 00, 00, 00, 38, fd
Status: WalkingPadCurStatus(dist=0.02, time=51, steps=73, speed=1.5, state=1, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Msg: f8, b2, 0f, 0d, 00, 33, 0a, 00, 49, 0e, 4e, 02, 00, 02, 0b, 00, 00, 81, 40, fd
Disconnecting
Msg: f8, b2, 05, 0a, 00, 4b, 0e, 54, 6e, fd
Msg: f8, b2, 03, 0d, 00, 35, f7, fd
Msg: f8, b2, 03, 0a, 00, 4d, 0c, fd
Msg: f8, b2, 03, 0a, 00, 4f, 0e, fd
192.168.178.27 - - [05/Feb/2023 17:50:36] "GET /mode?new_mode=automatic HTTP/1.1" 200 -
Connecting to 57:4C:4D:2E:0B:AB
Connecting to 57:4C:4D:2E:0B:AB
Connected: True
[Service] 0000180a-0000-1000-8000-00805f9b34fb: Device Information
	[Characteristic] 00002a28-0000-1000-8000-00805f9b34fb: (Handle: 13) (read) | Name: Software Revision String, Value: b'Hardware Revision\x00'
	[Characteristic] 00002a26-0000-1000-8000-00805f9b34fb: (Handle: 11) (read) | Name: Firmware Revision String, Value: b'M26_V187.1.2\x00'
	[Characteristic] 00002a25-0000-1000-8000-00805f9b34fb: (Handle: 9) (read) | Name: Serial Number String, Value: b'Serial Number\x00'
	[Characteristic] 00002a24-0000-1000-8000-00805f9b34fb: (Handle: 15) (read) | Name: Model Number String, Value: b'WLT8266M\x00'
	[Characteristic] 00002a29-0000-1000-8000-00805f9b34fb: (Handle: 17) (read) | Name: Manufacturer Name String, Value: b'Software Revision\x00'
[Service] 0000fe00-0000-1000-8000-00805f9b34fb: Vendor specific
	[Characteristic] 0000fe02-0000-1000-8000-00805f9b34fb: (Handle: 23) (write-without-response) | Name: Vendor specific, Value: None
	[Characteristic] 0000fe01-0000-1000-8000-00805f9b34fb: (Handle: 20) (read,notify) | Name: Vendor specific, Value: None
		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb: (Handle: 22) | Value: b'\x00\x00'
[Service] 00010203-0405-0607-0809-0a0b0c0d1912: Unknown
	[Characteristic] 00010203-0405-0607-0809-0a0b0c0d2b12: (Handle: 26) (read,write-without-response) | Name: Unknown, Value: b'\x00'
		[Descriptor] 00002901-0000-1000-8000-00805f9b34fb: (Handle: 28) | Value: b'OTA'
Enabling notification for 0000fe01-0000-1000-8000-00805f9b34fb
Service enumeration done
Msg: f8, a2, 03, 00, 01, 00, 00, 7b, 00, 00, 06, 00, 00, a9, 07, 00, 04, 00, db, fd
Status: WalkingPadCurStatus(dist=0.06, time=123, steps=169, speed=0.0, state=3, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
Msg: f8, b2, 0c, 09, 00, 0c, 00, 0d, 00, 7b, 0a, 00, a9, 0e, 00, 1c, fd
Msg: f8, b2, 07, 02, 00, 06, 0b, 00, 01, 74, 41, fd
Disconnecting
192.168.178.27 - - [05/Feb/2023 17:52:29] "GET /mode?new_mode=standby HTTP/1.1" 200 -
```

**Comment by huserben** [comment]
Hi @Turkules 

> I am not able to successfully change the mode of the Treadmill, what could be wrong here?

Do in general manage to connect to it, and just the changing of the mode is a problem? Or no connection to the pad is possible at all?

For the CSV export, you might look at the script code in [restserver](https://github.com/huserben/walkingpad/blob/main/restserver.py#L40). Feel free to adjust this to your needs, for example instead of storing the data in a database as I do to your CSV export.

**Comment by Turkules** [comment]
Thanks for the quick reply. Connection is possible like you can see in the log.

**Comment by huserben** [comment]
Hmm I can see that you are doing a `GET` request to change the mode: `GET /mode?new_mode=standby `

If you want to set it, you should use a `POST` (see https://github.com/huserben/walkingpad/blob/main/restserver.py#L126)

Can you try this and see if it helps?
